//! Phase 5 E2E fixture suite — per-fixture roundtrip tests.
//!
//! Each test loads a `.binpb` payload from `test_functional/fixtures/nemo/`,
//! posts it through OTLP, waits for the trace to land in storage, queries it
//! back via the public API, and asserts every field declared in the
//! companion `.meta.json`.
//!
//! Fixtures are synthetic for now (generated by
//! `cargo run -p zradar-functional-tests --bin gen_nemo_fixtures`); they
//! will be replaced by real-captured `.binpb` payloads when the OQ20 cron
//! infra exists per spec §3.3.
//!
//! `nat_dangling_span` is intentionally absent — it lives with the reaper
//! (deferred to Phase 5.5 / 6 since the reaper needs the libSQL Hot Store).

#[allow(unused_imports)]
use crate::*;

use anyhow::{Context, Result, anyhow};
use opentelemetry_proto::tonic::collector::logs::v1::ExportLogsServiceRequest;
use opentelemetry_proto::tonic::collector::trace::v1::ExportTraceServiceRequest;
use prost::Message;
use serde_json::Value;

/// The path prefix under which the fixture builder writes `.binpb` +
/// `.meta.json` pairs. Resolved relative to the test_functional crate so the
/// path works whether tests are run from the workspace root or from inside
/// `test_functional/`.
fn fixture_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("nemo")
}

/// Read `<name>.binpb` + `<name>.meta.json`.
fn load_fixture(name: &str) -> Result<(Vec<u8>, Value)> {
    let dir = fixture_dir();
    let binpb = std::fs::read(dir.join(format!("{name}.binpb")))
        .with_context(|| format!("read fixture {name}.binpb"))?;
    let meta_raw = std::fs::read_to_string(dir.join(format!("{name}.meta.json")))
        .with_context(|| format!("read fixture {name}.meta.json"))?;
    let meta: Value =
        serde_json::from_str(&meta_raw).with_context(|| format!("parse {name}.meta.json"))?;
    Ok((binpb, meta))
}

/// Extract every trace_id referenced by the spans in this trace fixture.
/// We need the IDs to poll the right endpoint after ingest; the meta.json
/// doesn't carry them (the fixture builder writes the same trace_id into
/// every span of a given fixture).
fn first_trace_id_hex(req: &ExportTraceServiceRequest) -> Option<String> {
    req.resource_spans
        .first()?
        .scope_spans
        .first()?
        .spans
        .first()
        .map(|s| hex::encode(&s.trace_id))
}

fn first_trace_id_hex_logs(req: &ExportLogsServiceRequest) -> Option<String> {
    req.resource_logs
        .first()?
        .scope_logs
        .first()?
        .log_records
        .first()
        .map(|l| hex::encode(&l.trace_id))
}

/// Skip fields that aren't exposed on `SpanDetail` today but live only in
/// the underlying Parquet row. The meta files describe the *ideal* surface;
/// this list is a known-divergence allowlist that gets re-evaluated when
/// `SpanDetail` adds fields.
const SPANDETAIL_NOT_EXPOSED: &[&str] = &["action_has_llm_calls"];

/// Assert that every field in `expected_fields` (a JSON object) matches the
/// corresponding field on `actual_span`. Reports the first mismatch with a
/// concrete value so the failure is actionable.
fn assert_span_fields(
    fixture: &str,
    span_name: &str,
    actual_span: &Value,
    expected_fields: &Value,
) -> Result<()> {
    let expected_obj = expected_fields
        .as_object()
        .ok_or_else(|| anyhow!("{fixture}/{span_name}: meta `fields` must be an object"))?;
    for (key, expected_value) in expected_obj {
        if SPANDETAIL_NOT_EXPOSED.contains(&key.as_str()) {
            continue;
        }
        let actual = actual_span.get(key).ok_or_else(|| {
            anyhow!("{fixture}/{span_name}: missing field `{key}` (expected {expected_value})")
        })?;
        if actual != expected_value {
            return Err(anyhow!(
                "{fixture}/{span_name}: field `{key}` mismatch — expected {expected_value}, got {actual}"
            ));
        }
    }
    Ok(())
}

/// Given a trace JSON returned by `/api/v1/traces/{id}`, return the first
/// span whose name matches the expectation entry's `span_name`.
///
/// The API surfaces span name as `operation_name` (see `SpanDetail`), while
/// the meta files use the spec's term `span_name` (matches the OTLP and
/// internal `Span` field). We translate here so the meta stays readable.
/// `span_name_prefix` is honored for forward-compatibility with spec
/// examples that match on a prefix.
fn find_expected_span<'a>(trace: &'a Value, expected: &Value) -> Option<&'a Value> {
    let spans = trace.get("spans")?.as_array()?;
    let api_name_field = "operation_name";
    if let Some(name) = expected.get("span_name").and_then(|v| v.as_str()) {
        return spans
            .iter()
            .find(|s| s.get(api_name_field).and_then(|v| v.as_str()) == Some(name));
    }
    if let Some(prefix) = expected.get("span_name_prefix").and_then(|v| v.as_str()) {
        return spans.iter().find(|s| {
            s.get(api_name_field)
                .and_then(|v| v.as_str())
                .is_some_and(|n| n.starts_with(prefix))
        });
    }
    None
}

/// Common assertion path for trace-kind fixtures.
async fn assert_trace_fixture(env: &TestEnv, fixture_name: &str) -> Result<()> {
    let (bytes, meta) = load_fixture(fixture_name)?;
    let req = ExportTraceServiceRequest::decode(bytes.as_slice())
        .with_context(|| format!("decode {fixture_name}.binpb"))?;

    let trace_id_hex = first_trace_id_hex(&req)
        .ok_or_else(|| anyhow!("{fixture_name}: no trace_id in fixture"))?;

    env.otlp
        .export_traces(req)
        .await
        .with_context(|| format!("{fixture_name}: export_traces"))?;

    let trace = wait_for_trace_default(&env.client, &trace_id_hex)
        .await
        .with_context(|| format!("{fixture_name}: wait_for_trace {trace_id_hex}"))?;

    let expected_total = meta
        .get("expected_total_spans")
        .and_then(|v| v.as_u64())
        .ok_or_else(|| anyhow!("{fixture_name}: meta.expected_total_spans missing"))?;
    let actual_total = trace
        .get("spans")
        .and_then(|v| v.as_array())
        .map(|v| v.len() as u64)
        .unwrap_or(0);
    if actual_total != expected_total {
        return Err(anyhow!(
            "{fixture_name}: expected {expected_total} spans, got {actual_total}"
        ));
    }

    let expectations = meta
        .get("expected_attributes")
        .and_then(|v| v.as_array())
        .ok_or_else(|| anyhow!("{fixture_name}: meta.expected_attributes missing/not an array"))?;
    for expected in expectations {
        let span = find_expected_span(&trace, expected).ok_or_else(|| {
            anyhow!(
                "{fixture_name}: no span matching {} found in trace",
                expected
                    .get("span_name")
                    .or_else(|| expected.get("span_name_prefix"))
                    .unwrap_or(&Value::Null)
            )
        })?;
        let span_name = expected
            .get("span_name")
            .and_then(|v| v.as_str())
            .or_else(|| expected.get("span_name_prefix").and_then(|v| v.as_str()))
            .unwrap_or("<unknown>");
        if let Some(fields) = expected.get("fields") {
            assert_span_fields(fixture_name, span_name, span, fields)?;
        }
    }
    Ok(())
}

/// Common assertion path for log-kind fixtures (evaluator_score). Posts the
/// log via OTLP gRPC and verifies it lands under the right trace. Since the
/// /scores endpoint is keyed on EvaluationScore writer behavior that varies
/// by phase, we deliberately keep this assertion narrow: trace_id of the
/// log was persisted, and `score_value` / `evaluator_name` flowed through.
async fn assert_logs_fixture(env: &TestEnv, fixture_name: &str) -> Result<()> {
    let (bytes, meta) = load_fixture(fixture_name)?;
    let req = ExportLogsServiceRequest::decode(bytes.as_slice())
        .with_context(|| format!("decode {fixture_name}.binpb"))?;
    let trace_id_hex = first_trace_id_hex_logs(&req)
        .ok_or_else(|| anyhow!("{fixture_name}: no trace_id in log fixture"))?;

    env.otlp
        .export_logs(req)
        .await
        .with_context(|| format!("{fixture_name}: export_logs"))?;

    // We poll the logs endpoint until at least one log under the fixture
    // trace shows up. The shape of the response (`/api/v1/logs?trace_id=...`)
    // varies — keep the assertion to "we got at least one row" plus the
    // expected_log_count from meta.
    let expected_log_count = meta
        .get("expected_log_count")
        .and_then(|v| v.as_u64())
        .ok_or_else(|| anyhow!("{fixture_name}: meta.expected_log_count missing"))?;

    let url = format!("/api/v1/logs?trace_id={trace_id_hex}");
    let items = wait_for_items_default(&env.client, &url)
        .await
        .with_context(|| format!("{fixture_name}: wait_for_items {url}"))?;

    if (items.len() as u64) < expected_log_count {
        return Err(anyhow!(
            "{fixture_name}: expected {expected_log_count} log(s) for trace {trace_id_hex}, got {}",
            items.len()
        ));
    }
    Ok(())
}

// ===========================================================================
// Per-fixture tests
// ===========================================================================

async fn test_fixture_guardrails_input_halt_body(env: TestEnv) -> Result<()> {
    assert_trace_fixture(&env, "guardrails_input_halt").await
}

dual_transport_test!(
    test_fixture_guardrails_input_halt,
    test_fixture_guardrails_input_halt_body
);

async fn test_fixture_guardrails_action_passthrough_body(env: TestEnv) -> Result<()> {
    assert_trace_fixture(&env, "guardrails_action_passthrough").await
}

dual_transport_test!(
    test_fixture_guardrails_action_passthrough,
    test_fixture_guardrails_action_passthrough_body
);

async fn test_fixture_nat_simple_workflow_body(env: TestEnv) -> Result<()> {
    assert_trace_fixture(&env, "nat_simple_workflow").await
}

dual_transport_test!(
    test_fixture_nat_simple_workflow,
    test_fixture_nat_simple_workflow_body
);

async fn test_fixture_nat_multi_function_body(env: TestEnv) -> Result<()> {
    assert_trace_fixture(&env, "nat_multi_function").await
}

dual_transport_test!(
    test_fixture_nat_multi_function,
    test_fixture_nat_multi_function_body
);

async fn test_fixture_openinference_langchain_body(env: TestEnv) -> Result<()> {
    assert_trace_fixture(&env, "openinference_langchain").await
}

dual_transport_test!(
    test_fixture_openinference_langchain,
    test_fixture_openinference_langchain_body
);

async fn test_fixture_evaluator_score_body(env: TestEnv) -> Result<()> {
    assert_logs_fixture(&env, "evaluator_score").await
}

dual_transport_test!(
    test_fixture_evaluator_score,
    test_fixture_evaluator_score_body
);

// ===========================================================================
// Sanity test: every fixture file is loadable + decodable. Doesn't require
// a running server, so it stays out of `#[ignore]` — runs in `cargo test`.
// ===========================================================================

#[test]
fn fixtures_are_loadable() -> Result<()> {
    let trace_fixtures = [
        "guardrails_input_halt",
        "guardrails_action_passthrough",
        "nat_simple_workflow",
        "nat_multi_function",
        "openinference_langchain",
    ];
    for name in trace_fixtures {
        let (bytes, meta) = load_fixture(name)?;
        let req = ExportTraceServiceRequest::decode(bytes.as_slice())
            .with_context(|| format!("decode {name}.binpb"))?;
        assert!(
            !req.resource_spans.is_empty(),
            "{name}: empty resource_spans"
        );
        assert_eq!(
            meta.get("fixture").and_then(|v| v.as_str()),
            Some(name),
            "{name}: meta.fixture field mismatch"
        );
        assert_eq!(meta.get("kind").and_then(|v| v.as_str()), Some("traces"));
    }

    let (bytes, meta) = load_fixture("evaluator_score")?;
    let req = ExportLogsServiceRequest::decode(bytes.as_slice())?;
    assert!(!req.resource_logs.is_empty());
    assert_eq!(meta.get("kind").and_then(|v| v.as_str()), Some("logs"));
    Ok(())
}
