#!/bin/sh

echo "Running pre-commit checks..."

# Formatting
echo "Formatting code..."
just fmt
if [ $? -ne 0 ]; then
  echo "Formatting failed."
  exit 1
fi

# Check clippy
echo "Checking clippy..."
just lint
if [ $? -ne 0 ]; then
  echo "Clippy check failed."
  exit 1
fi

# Check compilation
echo "Checking compilation..."
just check
if [ $? -ne 0 ]; then
  echo "Compilation check failed."
  exit 1
fi

echo "All checks passed!"
exit 0
